name: Build

on: [push]

jobs:
  build:
    name: Python ${{ matrix.python-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.7]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install wrangle
        pip install numpy
    - name: Run
      run: |
        python etl/etl.py
    - name: Deploy
        git checkout -b "auto_update_from_etl"
        git add --all
        git commit -m "update data based on ETL change"
        git push --set-upstream origin auto_update_from_etl
